"""Seed the blog database with a set of professional, technical articles.

Rebuilds blog.db (drops existing content) and inserts a starter set of
well-written developer posts. Run:

    source .venv/bin/activate
    python scripts/seed_professional.py
"""
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from database import init_schema  # noqa: E402
from models import create_article  # noqa: E402
from slug import slugify  # noqa: E402

DB = str(ROOT / "blog.db")

ARTICLES = [
    {
        "title": "SQLite in Production: A Pragmatic Field Guide",
        "tags": ["sqlite", "databases"],
        "body": """SQLite is often dismissed as a toy, yet it powers some of the most
scaled systems on the planet. The key is understanding exactly where it fits.

## When SQLite is the right call

Reach for SQLite when your workload is a *single writer with many readers* and
your data fits comfortably on one machine. This describes the majority of
small-to-mid applications, internal tools, and personal projects. The absence
of a separate server process removes an entire class of operational surface
area: there is no connection pool to tune, no query planner daemon to monitor,
and backups are literally a file copy.

## Configuration that matters

Two pragmas change the character of the database significantly:

```sql
PRAGMA journal_mode = WAL;
PRAGMA foreign_keys = ON;
```

WAL (write-ahead logging) allows readers to proceed without blocking the sole
writer, which is the difference between a fragile demo and a responsive
application. Foreign keys, which are off by default, protect referential
integrity and should be enabled on every connection from day one.

## Indexing discipline

Index every column you filter, join, or order by:

```sql
CREATE INDEX idx_articles_created ON articles(created_at DESC);
CREATE INDEX idx_articles_slug ON articles(slug);
```

An order-of-magnitude query win is usually one missing index away.

## Backups

The SQLite library writes to the database file directly, so coordinate backups
with the `sqlite3` interactive command rather than a naive `cp`, which can
capture a torn state mid-write:

```
sqlite3 blog.db '.backup blog.backup.db'
```

SQLite will not scale to multi-writer clusters, and for those workloads you
have honest options in PostgreSQL and friends. For everything else, it is a
pragmatic, boring-by-design workhorse."""
    },
    {
        "title": "Hardening a Flask Application: Sessions, CSRF, and Safe Rendering",
        "tags": ["flask", "security"],
        "body": """A web application degrades silently when security is treated as an
afterthought. The good news is that a disciplined Flask codebase can be made
defensible with a small set of deliberate choices.

## Never trust the session secret

Flask signs its session cookie with `SECRET_KEY`. Ship a default in code and
anyone with a copy of the source can forge sessions. Load it from the
environment at boot:

```python
SECRET_KEY = os.environ["SECRET_KEY"]
```

Treat the key like a credential: rotate it, store it outside the repository,
and use a different value per environment.

## Password hashing

Store only hash, never plaintext. Werkzeug's `generate_password_hash` uses a
key-derivation function that resists brute force. Always pick an explicit,
portable method so you are not coupled to host-specific primitives:

```python
from werkzeug.security import generate_password_hash, check_password_hash
hash_value = generate_password_hash(password, method="pbkdf2:sha256")
```

## CSRF on every state-changing request

Synchroniser tokens generated by session and checked on each POST stops
cross-site request forgery. Store the token in the session, embed it as a
hidden field, and compare with a constant-time comparison.

## Render content safely

User-authored Markdown must pass through an allowlist-based sanitizer before it
hits the template. Allow specific tags and protocols and strip everything else;
never pipe raw user HTML into `|safe`.

Parameterise every SQL query. Concatenating user input into a query string is
the single fastest way to lose a database, and it is also the easiest to avoid:
use query parameters at every point, without exception."""
    },
    {
        "title": "Full-Text Search with SQLite FTS5",
        "tags": ["sqlite", "search"],
        "body": """Writing a search feature usually conjures images of dedicated search
engines. In practice SQLite's `FTS5` extension delivers fast, offline full-text
search with zero external infrastructure for most content-driven products.

## Anatomy of an FTS table

An FTS virtual table stores tokenized text that can be matched efficiently.
The classic arrangement is an external-content table tied to a normal table so
search and your source of truth stay in sync:

```sql
CREATE VIRTUAL TABLE articles_fts USING fts5(
    title, content,
    content='articles',
    content_rowid='id'
);
```

## Keeping it in sync with triggers

Because the index is external content, you are responsible for updating it. The
cleanest way is triggers that fire on every insert, update, and delete:

```sql
CREATE TRIGGER articles_ai AFTER INSERT ON articles BEGIN
  INSERT INTO articles_fts(rowid, title, content)
  VALUES (new.id, new.title, new.content_md);
END;
```

The same pattern repeats for delete and update.

## Querying

Use `MATCH` to hit the index and `bm25` for relevance ranking:

```sql
SELECT a.* FROM articles_fts
  JOIN articles a ON a.id = articles_fts.rowid
WHERE articles_fts MATCH 'sqlite'
ORDER BY rank;
```

The built-in ranking requires a tokenizer-friendly query; for simple
single-term search, the `simple` tokenizer behaves predictably and is a good
default for developer content.

FTS5 is not a distributed search engine, but for a single-instance blog,
knowledge base, or documentation site it removes an entire search service from
your architecture."""
    },
    {
        "title": "A Pragmatic Introduction to Modern Python Typing",
        "tags": ["python"],
        "body": """Type hints went from an optional aesthetic to a genuine engineering tool for
API verification and refactoring safety. The value is real whether or not a
project is large.

## The minimum you should adopt

Start with function signatures. Annotated parameters and returns document the
contract readers must know:

```python
def fetch_page(db_path: str, limit: int, offset: int = 0) -> list[dict]:
    ...
```

`list[dict]` and `dict[str, str]` in Python 3.9+ replace the older `typing.List`
/ `typing.Dict` aliases.

## Union and Optional

For a value that can be absent, be explicit:

```python
from typing import Optional
def get_user_by_username(username: str) -> Optional[dict] | None:
    ...
```

Prefer `X | None` for the `|` syntax available in 3.10+, and `Optional[X]` for
older interpreters. Whatever you choose, stay consistent within a codebase.

## When hints become tests

Types only help if they are checked. Add a tool that runs the type model over
your code in CI, just like your test suite:

```bash
uvm --strict src tests
```

Type checking catches a category of slip that a unit test rarely does, because
it walks every code path, not just the ones your tests happen to exercise.

Adopt typing in layers: function signatures first, then data containers, then
full strict mode. The discipline compounds, and your future self — and your
colleagues — will thank you."""
    },
    {
        "title": "Git Worktrees: Develop in Isolation Without Branch Confusion",
        "tags": ["git", "workflows"],
        "body": """A single working directory is the reason developers feel anxious about
switching between feature branches. Git worktrees let you check out multiple of
your branches in separate directories at the same time, each with its own
working tree, all backed by one repository.

## The core idea

A `git worktree add` creates a new working directory plus a branch pointing at
shared object storage:

```bash
git worktree add ../feature-x -b feature-x
```

You now have `main` and `feature-x` checked out simultaneously. There is no
context-switching, no stashing, and nothing half-finished on your main branch;
you just `cd` into the other directory.

## Why it matters

- **Isolation without ceremony** — new work never touches your current branch,
  so a half-finished experiment cannot leak into unrelated changes.
- **Verifiable integration** — run the test suite in the feature's directory
  before merging, and again in the main directory after.
- **Clean archaeology** — discarded explorations are removed with the working
tree rather than lingering as stray changes you have to reason about later.

## Managing them

List and remove:

```bash
git worktree list
git worktree remove ../feature-x
git worktree prune   # clean stale registrations
```

## A pragmatic rule of thumb

Keep the local path outside the repository (or inside a gitignored directory)
so worktree artefacts never accidentally reach a commit. For a solo or small
team, worktrees are the lowest-friction way to run parallel ideas safely.

One caution: the ref for a branch can be modified by any constructed operation,
so never run destructive paths from within a worktree you might discard."""
    },
    {
        "title": "Design Systems for Developers: Make Interfaces Read Like Code",
        "tags": ["design", "frontend"],
        "body": """A design system is often taught as a set of colors and components, but its
real value resembles the value of a good type system: it constrains express
freedom so that coherence emerges.

## Tokens are the interface

Design tokens are the semantic variables your whole UI composes against. Put
palette, type, and spacing decisions into named variables and never hardcode a
value again:

```css
:root {
  --panel: #1d221b;
  --text: #eef1e7;
  --accent: #ffb84d;
  --radius: 10px;
}
```

Treat these tokens like an API contract: changes happen in one place and
propagate everywhere, and the dashboard of who overrides what stays visible.

### A single signature

The most effective interfaces are quiet everywhere except one recognisable
detail. Pick one signature element — a caret, a rail, a typeface — and repeat it
with discipline. Everything else should yield to typography and spacing.

### Let the medium inform the identity

A tool written for developers can carry developer vernacular in its UI: mono
type for data, brackets around tags, prompt prefixes. These choices are not
decoration; they encode information a reader already speaks.

### Respect motion and accessibility as a floor, not a ceiling

Honour `prefers-reduced-motion`, ship visible focus states, and keep contrast
AA. These are not finishing touches; they are the difference between a design
that coerces with CSS and one built for people."""
    },
    {
        "title": "Modeling Relational Data Without an ORM",
        "tags": ["sql", "databases"],
        "body": """An ORM is convenient until the mental model between your objects and your
query planner diverge. For many applications, a thin data-access layer over
SQL generates the smallest surface area and the fewest surprises.

## The shape of a data-access layer

Encapsulate every query in a function that owns its SQL and its parameters:

```python
def list_articles(limit: int, offset: int) -> list[sqlite3.Row]:
    conn = get_connection()
    return conn.execute(
        "SELECT * FROM articles ORDER BY created_at DESC LIMIT ? OFFSET ?",
        (limit, offset),
    ).fetchall()
```

Parameterise every input, always. This is where injection attacks are born and
where they are finally defeated.

## Associated entities are explicit

Managing a relational join is a query, not a magic method:

```sql
SELECT a.* FROM articles a
JOIN article_tags at ON at.article_id = a.id
JOIN tags t ON t.id = at.tag_id
WHERE t.name = ? ORDER BY a.created_at DESC;
```

You get to see the join algebra in full, with no opacity about what indexes are
in play.

## Transaction discipline

Batch state changes under one connection:

```python
with sqlite3.connect(db) as conn:
    for tag in tags:
        conn.execute("INSERT OR IGNORE INTO tags(name) VALUES (?)", (tag,))
```

A single transaction either commits entirely or rolls the whole operation back.

## Why this choice ages well

- **Transparent performance** — the query you read is the query that runs.
- **Small indirection** — few abstractions, so behavior is preserved across
  upgrades.
- **One less dependency** — one fewer pinned library with a versioned API.

When your joins become painful, an ORM can be introduced later to pay down the
conceptual debt. Start explicit; the query language is mature, portable and,
unlike most abstractions, will outlast the framework everyone is encouraging us
to use this year."""
    },
    {
        "title": "The Quiet Superpower of Writing Tests First",
        "tags": ["testing", "python"],
        "body": """Test-driven development is easy to describe and surprisingly hard to sustain,
yet on a personal project it is the highest-leverage discipline available. The
reason is not the tests themselves; it is the design pressure they create.

## The red step forces decisions

Writing a test before the code forces you to decide what the module's contract
is — what it accepts, what it returns, and what failure looks like. Those
decisions get made on paper, where they are cheap, instead of buried in an
implementation you later have to untangle.

```python
def test_search_finds_matching_title():
    result = search("sqlite")
    assert result[0]["title"] == "SQLite in Production"
```

## The barbecue of a fresh reviewer

Tests are the executable documentation. They show every future reader, and
every future version of you, what a function is expected to do — better than
any comment for the simple reason that they run.

## Working with fixtures

A temporary database keeps tests hermetic so they never touch real data:

```python
@pytest.fixture
def app(tmp_path):
    return create_app({"DATABASE": str(tmp_path / "test.db"), "TESTING": True})
```

Every test starts from a known baseline and cleans up after its run.

## The compounding effect

A codebase with a green test suite supports change without fear. When someone
(you, six months on) refactors a join or renames a route, the suite gives an
instant, mechanical survey of what matters. Without it, confidence is
long-term memory, ear, and hope — all of which rust.

Tests are not a step appended to, a task that touches real bugs, or a hoop to
jump. They are the discipline that turns a library of code into a system you
can trust yourself. Write the failing test first, watch it turn green, and
refactor with your eyes open."""
    },
]


def main() -> None:
    if os.path.exists(DB):
        os.remove(DB)
    init_schema(DB)
    for item in ARTICLES:
        excerpt = _first_paragraph(item["body"])
        create_article(
            item["title"],
            slugify(item["title"]),
            item["body"],
            excerpt,
            item["tags"],
            db_path=DB,
        )
    n = len(ARTICLES)
    print(f"Seeded {n} professional articles into {DB}")


def _first_paragraph(markdown: str) -> str:
    for line in markdown.split("\n"):
        line = line.strip()
        if line and not line.startswith("#"):
            return line[:160]
    return ""


if __name__ == "__main__":
    main()